# Welcome to Jekyll!

# Website settings
title: "Jiangxh"
description: "蒋信厚的独立博客"
keywords: "蒋信厚,jiangxh,blog,Unity,Github,IOS,VR,AR"

baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'static/img/blog'

# author
author:
  name: 'Jiangxh'
  first_name: 'Xinhou'
  last_name: 'Jiang'
  email: 'jiangxinhou@outlook.com'
  facebook_username: 'Jiang Xinhou'
  github_username: 'jiangxh1992'
  head_img: 'static/img/landing/me.jpg'

# social link
fenglele:
  first_name: 'Lele'
  last_name: 'Feng'
  description: 'Computer Grapics'
  link: 'http://candycat1992.github.io'
  email: 'lelefeng@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  p1:
    name: 'JXHDemo'
    url: '/jiangxh1992/JXHDemo'
    img: 'static/img/projects/p1.png'
  p2:
    name: 'SpaceWar'
    url: '/jiangxh1992/SpaceWar'
    img: 'static/img/projects/p2.png'
  p3:
    name: 'WorldFind'
    url: '/jiangxh1992/WorldFind'
    img: 'static/img/projects/p3.png'
  p4:
    name: 'STICKHERO'
    url: '/jiangxh1992/STICKHERO'
    img: 'static/img/projects/p4.png'
  p5:
    name: 'OpenGLDemo'
    url: '/jiangxh1992/OpenGLDemo'
    img: 'static/img/projects/p5.png'
  p6:
    name: 'SDKDemo'
    url: '/jiangxh1992/SDKDemo'
    img: 'static/img/projects/p6.png'
  p7:
    name: 'FourInRowGame'
    url: '/jiangxh1992/FourInRowGame'
    img: 'static/img/projects/p7.png'

# blog index
index:
  one: 'New'
  two: 'Unity3d'
  three: 'IOS'
  four: 'About Me'
  five: 'Academic'
  six: 'OpenGL'
  seven: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jiangxh
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
